#!/bin/bash

#TODO change wlan0 to your own interface if `wlan0` is not your default interface
#use this script if airmon-ng cannot set wireless interface to managed type
#use this script if airodump-ng cannot scan wireless networks (shows nothing)
ip link set wlan0 down
sleep 1
iw wlan0 set type managed
sleep 1
ip link set wlan0 up
sleep 1
systemctl restart NetworkManager
sleep 5
iwconfig
sleep 1 
##airodump-ng wlan0
